#! /bin/sh

if [ $# -lt 2 ] ; then
  echo "usage: $0 <problem_name> <exe_dir>"
  echo "where problem_name is from:"
  echo "   tester  qptestmain "
  exit 1
fi

# $1 (first  argument) is the name of the problem
# $2 (second argument) is the directory containing executables

CURDIR=$PWD
PROBLEM=$1
EXEDIR=$2

if test ! -f  $EXEDIR/$PROBLEM
then
   echo "Error: \"$PROBLEM\" is an unrecognized problem."
   exit 1
fi

#
# Copy data files into the executable directory
#

if test -f  $PROBLEM.opt
then
   cp $PROBLEM.opt $EXEDIR/
fi

#
# Execute the example
#

cd $EXEDIR
./$PROBLEM
if test -f  $PROBLEM.out
then
   cp -f $PROBLEM.out $CURDIR/
fi

