#!/bin/sh

QPOPT=$HOME/qpopt
PROBLEM=$QPOPT/examples
SRCDIR=$QPOPT/src

ftnchek -array=2 $PROBLEM/qpoptmain.f \
                 $SRCDIR/mcsubs.f     \
                 $SRCDIR/opsubs.f     \
                 $SRCDIR/blas1.f      \
                 $SRCDIR/blas2.f      \
                 $SRCDIR/f06subs.f    \
                 $SRCDIR/cmsubs.f     \
                 $SRCDIR/utcomsubs.f  \
                 $SRCDIR/rzsubs.f     \
                 $SRCDIR/lpoptsubs.f  \
                 $SRCDIR/qpoptsubs.f
