#!/bin/sh

QPOPT=$HOME/qpopt
PROBLEM=$QPOPT/examples
SRC=$QPOPT/src
DOS=$QPOPT/DOS

cp -p $PROBLEM/lpoptmain.opt $DOS/lpmain.opt
cp -p $PROBLEM/qpoptmain.opt $DOS/qpmain.opt
cp -p $PROBLEM/lpoptmain.f   $DOS/lpmain.for
cp -p $PROBLEM/qpoptmain.f   $DOS/qpmain.for
cp -p $SRC/mcsubs.f          $DOS/mcsubs.for
cp -p $SRC/opsubs.f          $DOS/opsubs.for
cp -p $SRC/blas1.f           $DOS/blas1.for
cp -p $SRC/blas2.f           $DOS/blas2.for
cp -p $SRC/f06subs.f         $DOS/f06subs.for
cp -p $SRC/cmsubs.f          $DOS/cmsubs.for
cp -p $SRC/utcomsubs.f       $DOS/utsubs.for
cp -p $SRC/rzsubs.f          $DOS/rzsubs.for
cp -p $SRC/lpoptsubs.f       $DOS/lpsubs.for
cp -p $SRC/qpoptsubs.f       $DOS/qpsubs.for
